import { Sora } from "next/font/google";

import type { Metadata } from "next";

import "./globals.css";

import Navbar from "./components/Navbar";

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sora.className} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
